AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  my service test

Globals:
  Function:
    Timeout: 5
    Tracing: Active
    MemorySize: 1024
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
      AllowOrigin: "'*'"
    
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL

  GetNames:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/get-user/
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          TABLE_NAME: !Ref NamesTable
      Events:
        GetUsersAPICall:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref NamesTable

  NamesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH

  NewNameTopic:
    Type: AWS::SNS::Topic
    
  AddName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/add-user/
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          TABLE_NAME: !Ref NamesTable
          TOPIC_NAME: !Ref NewNameTopic
      Events:
        AddUserAPICall:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /users
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref NamesTable
        - SNSPublishMessagePolicy:
            TopicName: !Sub ${NewNameTopic.TopicName}

  ListenerNewName:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: users/notify-user/
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        Listener:
          Type: SNS
          Properties:
            Topic: !Ref NewNameTopic
            FilterPolicy:
              Status:
                - Success
  

Outputs:
  ProdApiEndpoint:
    Description: "API Prod stage endpoint"
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/Prod/"